server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka